"""Markdown to DOCX converter for Russian legal documents.

Converts Markdown text (generated by Claude LLM) into professionally
styled DOCX files suitable for legal use.
"""
from __future__ import annotations

import io
import logging
import re
import zipfile

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Mm, Pt

logger = logging.getLogger(__name__)

# ── Regex patterns for Markdown parsing ──────────────────────────

RE_HEADING = re.compile(r"^(#{1,3})\s+(.+)$")
RE_HORIZONTAL_RULE = re.compile(r"^-{3,}\s*$")
RE_BULLET_ITEM = re.compile(r"^(\s*)[-*]\s+(.+)$")
RE_NUMBERED_ITEM = re.compile(r"^(\s*)(\d+[\.\)]\s*)(.+)$")
RE_TABLE_ROW = re.compile(r"^\|(.+)\|\s*$")
RE_TABLE_SEPARATOR = re.compile(r"^\|[\s\-:|]+\|\s*$")
RE_BOLD = re.compile(r"\*\*(.+?)\*\*")
RE_ITALIC = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")
RE_BLANK_LINE = re.compile(r"^\s*$")


class MarkdownToDocxConverter:
    """Converts Markdown text to a styled DOCX document for Russian legal documents."""

    def __init__(self, title: str = "", organization_name: str = "") -> None:
        self.title = title
        self.organization_name = organization_name

    def convert(self, markdown_text: str) -> Document:
        """Convert markdown text to a python-docx Document object."""
        doc = Document()
        self._setup_styles(doc)
        self._setup_page(doc)
        self._setup_header_footer(doc)
        self._set_metadata(doc)

        lines = markdown_text.split("\n")
        self._process_lines(doc, lines)
        return doc

    def convert_to_bytes(self, markdown_text: str) -> bytes:
        """Convert markdown text to DOCX bytes (for HTTP response)."""
        doc = self.convert(markdown_text)
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()

    # ── Styles ───────────────────────────────────────────────────

    def _setup_styles(self, doc: Document) -> None:
        """Configure document styles for Russian legal documents."""
        # Normal text
        style = doc.styles["Normal"]
        style.font.name = "Times New Roman"
        style.font.size = Pt(12)
        style.paragraph_format.space_after = Pt(6)
        style.paragraph_format.space_before = Pt(0)
        style.paragraph_format.line_spacing = 1.15
        self._set_cyrillic_font(style, "Times New Roman")

        # Heading 1 — document title, centered
        h1 = doc.styles["Heading 1"]
        h1.font.name = "Times New Roman"
        h1.font.size = Pt(16)
        h1.font.bold = True
        h1.font.color.rgb = None  # Reset to auto (black)
        h1.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
        h1.paragraph_format.space_before = Pt(12)
        h1.paragraph_format.space_after = Pt(12)
        self._set_cyrillic_font(h1, "Times New Roman")

        # Heading 2 — section headings
        h2 = doc.styles["Heading 2"]
        h2.font.name = "Times New Roman"
        h2.font.size = Pt(14)
        h2.font.bold = True
        h2.font.color.rgb = None
        h2.paragraph_format.space_before = Pt(12)
        h2.paragraph_format.space_after = Pt(6)
        self._set_cyrillic_font(h2, "Times New Roman")

        # Heading 3 — subsection headings
        h3 = doc.styles["Heading 3"]
        h3.font.name = "Times New Roman"
        h3.font.size = Pt(13)
        h3.font.bold = True
        h3.font.color.rgb = None
        h3.paragraph_format.space_before = Pt(6)
        h3.paragraph_format.space_after = Pt(6)
        self._set_cyrillic_font(h3, "Times New Roman")

        # List Bullet style
        if "List Bullet" in doc.styles:
            lb = doc.styles["List Bullet"]
            lb.font.name = "Times New Roman"
            lb.font.size = Pt(12)
            self._set_cyrillic_font(lb, "Times New Roman")

        # List Number style
        if "List Number" in doc.styles:
            ln = doc.styles["List Number"]
            ln.font.name = "Times New Roman"
            ln.font.size = Pt(12)
            self._set_cyrillic_font(ln, "Times New Roman")

    @staticmethod
    def _set_cyrillic_font(style, font_name: str) -> None:
        """Ensure Cyrillic characters use the specified font."""
        rPr = style.element.get_or_add_rPr()
        rFonts = rPr.find(qn("w:rFonts"))
        if rFonts is None:
            rFonts = OxmlElement("w:rFonts")
            rPr.insert(0, rFonts)
        rFonts.set(qn("w:eastAsia"), font_name)
        rFonts.set(qn("w:cs"), font_name)

    # ── Page setup ───────────────────────────────────────────────

    def _setup_page(self, doc: Document) -> None:
        """Configure A4 page with GOST R 6.30-2003 margins."""
        section = doc.sections[0]
        section.page_width = Mm(210)
        section.page_height = Mm(297)
        section.top_margin = Mm(20)
        section.bottom_margin = Mm(20)
        section.left_margin = Mm(30)
        section.right_margin = Mm(15)

    # ── Header / Footer ──────────────────────────────────────────

    def _setup_header_footer(self, doc: Document) -> None:
        """Add organization name in header and page number in footer."""
        section = doc.sections[0]

        # Header with organization name
        if self.organization_name:
            section.different_first_page_header_footer = False
            header = section.header
            header.is_linked_to_previous = False
            header_para = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
            header_para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
            run = header_para.add_run(self.organization_name)
            run.font.name = "Times New Roman"
            run.font.size = Pt(9)
            run.font.italic = True
            self._set_run_cyrillic_font(run, "Times New Roman")

        # Footer with page number
        footer = section.footer
        footer.is_linked_to_previous = False
        footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = footer_para.add_run()
        fld_char_begin = OxmlElement("w:fldChar")
        fld_char_begin.set(qn("w:fldCharType"), "begin")
        run._element.append(fld_char_begin)

        instr = OxmlElement("w:instrText")
        instr.set(qn("xml:space"), "preserve")
        instr.text = " PAGE "
        run._element.append(instr)

        fld_char_end = OxmlElement("w:fldChar")
        fld_char_end.set(qn("w:fldCharType"), "end")
        run._element.append(fld_char_end)

    # ── Metadata ─────────────────────────────────────────────────

    def _set_metadata(self, doc: Document) -> None:
        """Set document core properties."""
        doc.core_properties.title = self.title
        doc.core_properties.author = self.organization_name
        doc.core_properties.language = "ru-RU"

    # ── Line processing ──────────────────────────────────────────

    def _process_lines(self, doc: Document, lines: list[str]) -> None:
        """Parse Markdown lines and render into the DOCX document."""
        i = 0
        paragraph_buffer: list[str] = []

        while i < len(lines):
            line = lines[i]

            # Blank line — flush paragraph buffer
            if RE_BLANK_LINE.match(line):
                self._flush_paragraph(doc, paragraph_buffer)
                paragraph_buffer = []
                i += 1
                continue

            # Heading
            m = RE_HEADING.match(line)
            if m:
                self._flush_paragraph(doc, paragraph_buffer)
                paragraph_buffer = []
                level = len(m.group(1))
                text = m.group(2).strip()
                self._render_heading(doc, level, text)
                i += 1
                continue

            # Horizontal rule
            if RE_HORIZONTAL_RULE.match(line):
                self._flush_paragraph(doc, paragraph_buffer)
                paragraph_buffer = []
                self._render_horizontal_rule(doc)
                i += 1
                continue

            # Table — accumulate rows
            if RE_TABLE_ROW.match(line):
                self._flush_paragraph(doc, paragraph_buffer)
                paragraph_buffer = []
                table_rows: list[str] = []
                while i < len(lines) and RE_TABLE_ROW.match(lines[i]):
                    table_rows.append(lines[i])
                    i += 1
                self._render_table(doc, table_rows)
                continue

            # Bullet list item
            m = RE_BULLET_ITEM.match(line)
            if m:
                self._flush_paragraph(doc, paragraph_buffer)
                paragraph_buffer = []
                indent = len(m.group(1))
                text = m.group(2).strip()
                self._render_bullet_item(doc, text, indent)
                i += 1
                continue

            # Numbered list item
            m = RE_NUMBERED_ITEM.match(line)
            if m:
                self._flush_paragraph(doc, paragraph_buffer)
                paragraph_buffer = []
                indent = len(m.group(1))
                prefix = m.group(2)
                text = m.group(3).strip()
                self._render_numbered_item(doc, prefix, text, indent)
                i += 1
                continue

            # Regular text — accumulate into paragraph
            paragraph_buffer.append(line)
            i += 1

        # Flush remaining
        self._flush_paragraph(doc, paragraph_buffer)

    def _flush_paragraph(self, doc: Document, buffer: list[str]) -> None:
        """Join accumulated lines into a single paragraph and render it."""
        if not buffer:
            return
        text = " ".join(line.strip() for line in buffer)
        if text.strip():
            para = doc.add_paragraph()
            self._add_formatted_runs(para, text)

    # ── Rendering methods ────────────────────────────────────────

    def _render_heading(self, doc: Document, level: int, text: str) -> None:
        """Add a heading paragraph."""
        heading = doc.add_heading(level=level)
        self._add_formatted_runs(heading, text)

    def _render_bullet_item(self, doc: Document, text: str, indent: int = 0) -> None:
        """Add a bullet list item."""
        para = doc.add_paragraph(style="List Bullet")
        if indent > 0:
            para.paragraph_format.left_indent = Cm(1.27 + indent * 0.5)
        self._add_formatted_runs(para, text)

    def _render_numbered_item(
        self, doc: Document, prefix: str, text: str, indent: int = 0,
    ) -> None:
        """Add a numbered list item with its original prefix."""
        para = doc.add_paragraph()
        if indent > 0:
            para.paragraph_format.left_indent = Cm(1.27 + indent * 0.5)
        # Add the number prefix as a run, then the text
        run = para.add_run(prefix)
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)
        self._set_run_cyrillic_font(run, "Times New Roman")
        self._add_formatted_runs(para, text)

    def _render_horizontal_rule(self, doc: Document) -> None:
        """Add a horizontal rule as a paragraph with bottom border."""
        para = doc.add_paragraph()
        para.paragraph_format.space_before = Pt(6)
        para.paragraph_format.space_after = Pt(6)
        # Add bottom border via XML
        pPr = para._element.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"), "single")
        bottom.set(qn("w:sz"), "4")
        bottom.set(qn("w:space"), "1")
        bottom.set(qn("w:color"), "999999")
        pBdr.append(bottom)
        pPr.append(pBdr)

    def _render_table(self, doc: Document, raw_rows: list[str]) -> None:
        """Render a pipe-delimited Markdown table as a DOCX table."""
        # Parse rows, skip separator
        parsed: list[list[str]] = []
        for row in raw_rows:
            if RE_TABLE_SEPARATOR.match(row):
                continue
            cells = [c.strip() for c in row.strip("|").split("|")]
            parsed.append(cells)

        if not parsed:
            return

        num_cols = max(len(row) for row in parsed)
        table = doc.add_table(rows=len(parsed), cols=num_cols)
        table.style = "Table Grid"

        for r_idx, row_data in enumerate(parsed):
            for c_idx, cell_text in enumerate(row_data):
                if c_idx < num_cols:
                    cell = table.cell(r_idx, c_idx)
                    cell.text = ""
                    para = cell.paragraphs[0]
                    self._add_formatted_runs(para, cell_text)
                    # Font for table cells
                    for run in para.runs:
                        run.font.name = "Times New Roman"
                        run.font.size = Pt(11)
                        self._set_run_cyrillic_font(run, "Times New Roman")

        # Bold the first row (header)
        if len(parsed) > 0:
            for cell in table.rows[0].cells:
                for para in cell.paragraphs:
                    for run in para.runs:
                        run.bold = True

    # ── Inline formatting ────────────────────────────────────────

    def _add_formatted_runs(self, paragraph, text: str) -> None:
        """Parse inline Markdown (bold, italic) and add runs to paragraph."""
        # Split text into segments: bold, italic, and plain
        # Pattern: **bold** or *italic*
        pattern = re.compile(r"(\*\*(.+?)\*\*|\*(.+?)\*)")
        pos = 0
        for m in pattern.finditer(text):
            # Add plain text before this match
            if m.start() > pos:
                plain = text[pos : m.start()]
                if plain:
                    run = paragraph.add_run(plain)
                    run.font.name = "Times New Roman"
                    run.font.size = Pt(12)
                    self._set_run_cyrillic_font(run, "Times New Roman")

            if m.group(2) is not None:
                # Bold text
                run = paragraph.add_run(m.group(2))
                run.bold = True
                run.font.name = "Times New Roman"
                run.font.size = Pt(12)
                self._set_run_cyrillic_font(run, "Times New Roman")
            elif m.group(3) is not None:
                # Italic text
                run = paragraph.add_run(m.group(3))
                run.italic = True
                run.font.name = "Times New Roman"
                run.font.size = Pt(12)
                self._set_run_cyrillic_font(run, "Times New Roman")

            pos = m.end()

        # Remaining plain text
        remaining = text[pos:]
        if remaining:
            run = paragraph.add_run(remaining)
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)
            self._set_run_cyrillic_font(run, "Times New Roman")

    @staticmethod
    def _set_run_cyrillic_font(run, font_name: str) -> None:
        """Ensure a specific run renders Cyrillic text in the correct font."""
        rPr = run._element.get_or_add_rPr()
        rFonts = rPr.find(qn("w:rFonts"))
        if rFonts is None:
            rFonts = OxmlElement("w:rFonts")
            rPr.insert(0, rFonts)
        rFonts.set(qn("w:eastAsia"), font_name)
        rFonts.set(qn("w:cs"), font_name)


# ── ZIP archive helper ───────────────────────────────────────────


def create_zip_archive(documents: list[dict], organization_name: str = "") -> bytes:
    """Create a ZIP archive containing DOCX files for all documents.

    Each dict in ``documents`` must have keys: doc_type, title, content_md.
    Returns ZIP file bytes.
    """
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for doc in documents:
            try:
                converter = MarkdownToDocxConverter(
                    title=doc.get("title", ""),
                    organization_name=organization_name,
                )
                docx_bytes = converter.convert_to_bytes(doc.get("content_md", ""))
                filename = f"{doc.get('doc_type', 'document')}.docx"
                zf.writestr(filename, docx_bytes)
            except Exception as e:
                logger.error("Failed to convert %s to DOCX: %s", doc.get("doc_type"), e)
                # Write error note into ZIP
                zf.writestr(
                    f"{doc.get('doc_type', 'document')}_ERROR.txt",
                    f"Conversion failed: {e}",
                )
    buffer.seek(0)
    return buffer.getvalue()
