"""Markdown to PDF converter for Russian legal documents.

Converts Markdown text (generated by LLM) into professionally styled
PDF files using reportlab.  Supports Cyrillic (Times New Roman),
headings, bold/italic, bullet/numbered lists, tables, and horizontal rules.
"""
from __future__ import annotations

import io
import logging
import os
import re

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# ── Font registration ────────────────────────────────────────────

_FONT_REGISTERED = False

# Possible paths for Times New Roman on different OS
_TNR_SEARCH_PATHS = [
    # macOS
    "/System/Library/Fonts/Supplemental/Times New Roman.ttf",
    "/System/Library/Fonts/Supplemental/Times New Roman Bold.ttf",
    "/System/Library/Fonts/Supplemental/Times New Roman Italic.ttf",
    "/System/Library/Fonts/Supplemental/Times New Roman Bold Italic.ttf",
    "/Library/Fonts/Times New Roman.ttf",
    "/Library/Fonts/Times New Roman Bold.ttf",
    "/Library/Fonts/Times New Roman Italic.ttf",
    "/Library/Fonts/Times New Roman Bold Italic.ttf",
    # Linux
    "/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman.ttf",
    "/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman_Bold.ttf",
    "/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman_Italic.ttf",
    "/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman_Bold_Italic.ttf",
    # Windows
    "C:/Windows/Fonts/times.ttf",
    "C:/Windows/Fonts/timesbd.ttf",
    "C:/Windows/Fonts/timesi.ttf",
    "C:/Windows/Fonts/timesbi.ttf",
]

FONT_FAMILY = "TimesNewRoman"


def _find_font(keyword: str) -> str | None:
    """Find a TTF file by keyword in the search paths."""
    kw = keyword.lower()
    for path in _TNR_SEARCH_PATHS:
        if kw in path.lower() and os.path.exists(path):
            return path
    return None


def _register_fonts() -> None:
    """Register Times New Roman variants for reportlab (Cyrillic support)."""
    global _FONT_REGISTERED
    if _FONT_REGISTERED:
        return

    regular = _find_font("times new roman.ttf") or _find_font("times_new_roman.ttf") or _find_font("times.ttf")
    bold = _find_font("bold.ttf") or _find_font("timesbd")
    italic = _find_font("italic.ttf") or _find_font("timesi")
    bold_italic = _find_font("bold italic") or _find_font("timesbi")

    if regular:
        pdfmetrics.registerFont(TTFont(FONT_FAMILY, regular))
        if bold:
            pdfmetrics.registerFont(TTFont(f"{FONT_FAMILY}-Bold", bold))
        if italic:
            pdfmetrics.registerFont(TTFont(f"{FONT_FAMILY}-Italic", italic))
        if bold_italic:
            pdfmetrics.registerFont(TTFont(f"{FONT_FAMILY}-BoldItalic", bold_italic))

        from reportlab.lib.fonts import addMapping
        addMapping(FONT_FAMILY, 0, 0, FONT_FAMILY)
        if bold:
            addMapping(FONT_FAMILY, 1, 0, f"{FONT_FAMILY}-Bold")
        if italic:
            addMapping(FONT_FAMILY, 0, 1, f"{FONT_FAMILY}-Italic")
        if bold_italic:
            addMapping(FONT_FAMILY, 1, 1, f"{FONT_FAMILY}-BoldItalic")

        logger.info("Registered Times New Roman fonts for PDF")
    else:
        logger.warning("Times New Roman not found, using Helvetica fallback")

    _FONT_REGISTERED = True


def _font_name() -> str:
    """Return the registered font family name."""
    _register_fonts()
    try:
        pdfmetrics.getFont(FONT_FAMILY)
        return FONT_FAMILY
    except KeyError:
        return "Helvetica"


# ── Regex patterns (reused from docx_converter) ─────────────────

RE_HEADING = re.compile(r"^(#{1,3})\s+(.+)$")
RE_HORIZONTAL_RULE = re.compile(r"^-{3,}\s*$")
RE_BULLET_ITEM = re.compile(r"^(\s*)[-*]\s+(.+)$")
RE_NUMBERED_ITEM = re.compile(r"^(\s*)(\d+[\.\)]\s*)(.+)$")
RE_TABLE_ROW = re.compile(r"^\|(.+)\|\s*$")
RE_TABLE_SEPARATOR = re.compile(r"^\|[\s\-:|]+\|\s*$")
RE_BLANK_LINE = re.compile(r"^\s*$")


# ── Styles ───────────────────────────────────────────────────────

def _build_styles() -> dict[str, ParagraphStyle]:
    """Build paragraph styles for the PDF."""
    font = _font_name()
    base = getSampleStyleSheet()

    styles = {
        "Normal": ParagraphStyle(
            "PDFNormal",
            parent=base["Normal"],
            fontName=font,
            fontSize=12,
            leading=16,
            spaceAfter=6,
            alignment=TA_LEFT,
        ),
        "Heading1": ParagraphStyle(
            "PDFH1",
            parent=base["Normal"],
            fontName=f"{font}-Bold" if font == FONT_FAMILY else font,
            fontSize=16,
            leading=20,
            spaceBefore=12,
            spaceAfter=12,
            alignment=TA_CENTER,
        ),
        "Heading2": ParagraphStyle(
            "PDFH2",
            parent=base["Normal"],
            fontName=f"{font}-Bold" if font == FONT_FAMILY else font,
            fontSize=14,
            leading=18,
            spaceBefore=12,
            spaceAfter=6,
            alignment=TA_LEFT,
        ),
        "Heading3": ParagraphStyle(
            "PDFH3",
            parent=base["Normal"],
            fontName=f"{font}-Bold" if font == FONT_FAMILY else font,
            fontSize=13,
            leading=17,
            spaceBefore=6,
            spaceAfter=6,
            alignment=TA_LEFT,
        ),
        "Bullet": ParagraphStyle(
            "PDFBullet",
            parent=base["Normal"],
            fontName=font,
            fontSize=12,
            leading=16,
            leftIndent=20,
            spaceAfter=3,
            bulletIndent=8,
        ),
        "Numbered": ParagraphStyle(
            "PDFNumbered",
            parent=base["Normal"],
            fontName=font,
            fontSize=12,
            leading=16,
            leftIndent=20,
            spaceAfter=3,
        ),
        "TableCell": ParagraphStyle(
            "PDFTableCell",
            parent=base["Normal"],
            fontName=font,
            fontSize=11,
            leading=14,
            spaceAfter=0,
        ),
        "TableHeader": ParagraphStyle(
            "PDFTableHeader",
            parent=base["Normal"],
            fontName=f"{font}-Bold" if font == FONT_FAMILY else font,
            fontSize=11,
            leading=14,
            spaceAfter=0,
        ),
    }
    return styles


# ── Inline formatting ────────────────────────────────────────────

def _md_inline_to_html(text: str) -> str:
    """Convert Markdown bold/italic to reportlab XML tags."""
    # Bold: **text** → <b>text</b>
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # Italic: *text* → <i>text</i>
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<i>\1</i>", text)
    # Escape remaining XML-sensitive chars
    # (do this first for & but after bold/italic conversion)
    return text


def _escape_xml(text: str) -> str:
    """Escape XML special characters for reportlab Paragraph."""
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    return text


def _format_text(text: str) -> str:
    """Escape XML, then apply Markdown inline formatting."""
    # We need to escape first, but preserve ** and * markers
    # Strategy: escape, then convert markers
    escaped = _escape_xml(text)
    return _md_inline_to_html(escaped)


# ── PDF converter ────────────────────────────────────────────────


class MarkdownToPdfConverter:
    """Converts Markdown text to a styled PDF document for Russian legal documents."""

    def __init__(self, title: str = "", organization_name: str = "") -> None:
        self.title = title
        self.organization_name = organization_name
        self.styles = _build_styles()

    def convert_to_bytes(self, markdown_text: str) -> bytes:
        """Convert Markdown text to PDF bytes."""
        buffer = io.BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
            leftMargin=30 * mm,
            rightMargin=15 * mm,
            title=self.title,
            author=self.organization_name,
        )

        elements = self._parse_markdown(markdown_text)
        doc.build(elements, onFirstPage=self._header_footer, onLaterPages=self._header_footer)
        buffer.seek(0)
        return buffer.getvalue()

    def _header_footer(self, canvas, doc):
        """Draw header (org name) and footer (page number) on each page."""
        canvas.saveState()
        font = _font_name()

        # Header — org name, right-aligned
        if self.organization_name:
            canvas.setFont(font, 9)
            canvas.drawRightString(
                A4[0] - 15 * mm,
                A4[1] - 12 * mm,
                self.organization_name,
            )

        # Footer — page number, centered
        canvas.setFont(font, 9)
        canvas.drawCentredString(
            A4[0] / 2,
            12 * mm,
            str(canvas.getPageNumber()),
        )
        canvas.restoreState()

    def _parse_markdown(self, markdown_text: str) -> list:
        """Parse Markdown lines into reportlab flowables."""
        lines = markdown_text.split("\n")
        elements: list = []
        i = 0
        paragraph_buffer: list[str] = []

        while i < len(lines):
            line = lines[i]

            # Blank line
            if RE_BLANK_LINE.match(line):
                self._flush_paragraph(elements, paragraph_buffer)
                paragraph_buffer = []
                i += 1
                continue

            # Heading
            m = RE_HEADING.match(line)
            if m:
                self._flush_paragraph(elements, paragraph_buffer)
                paragraph_buffer = []
                level = len(m.group(1))
                text = m.group(2).strip()
                style_name = f"Heading{level}"
                elements.append(Paragraph(_format_text(text), self.styles[style_name]))
                i += 1
                continue

            # Horizontal rule
            if RE_HORIZONTAL_RULE.match(line):
                self._flush_paragraph(elements, paragraph_buffer)
                paragraph_buffer = []
                # Draw a line using a thin table
                line_table = Table([[""]], colWidths=[165 * mm], rowHeights=[1])
                line_table.setStyle(TableStyle([
                    ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.grey),
                ]))
                elements.append(Spacer(1, 6))
                elements.append(line_table)
                elements.append(Spacer(1, 6))
                i += 1
                continue

            # Table
            if RE_TABLE_ROW.match(line):
                self._flush_paragraph(elements, paragraph_buffer)
                paragraph_buffer = []
                table_rows: list[str] = []
                while i < len(lines) and RE_TABLE_ROW.match(lines[i]):
                    table_rows.append(lines[i])
                    i += 1
                self._render_table(elements, table_rows)
                continue

            # Bullet list item
            m = RE_BULLET_ITEM.match(line)
            if m:
                self._flush_paragraph(elements, paragraph_buffer)
                paragraph_buffer = []
                text = m.group(2).strip()
                bullet_text = f"\u2022  {_format_text(text)}"
                elements.append(Paragraph(bullet_text, self.styles["Bullet"]))
                i += 1
                continue

            # Numbered list item
            m = RE_NUMBERED_ITEM.match(line)
            if m:
                self._flush_paragraph(elements, paragraph_buffer)
                paragraph_buffer = []
                prefix = m.group(2)
                text = m.group(3).strip()
                num_text = f"{_escape_xml(prefix)}{_format_text(text)}"
                elements.append(Paragraph(num_text, self.styles["Numbered"]))
                i += 1
                continue

            # Regular text
            paragraph_buffer.append(line)
            i += 1

        self._flush_paragraph(elements, paragraph_buffer)
        return elements

    def _flush_paragraph(self, elements: list, buffer: list[str]) -> None:
        if not buffer:
            return
        text = " ".join(line.strip() for line in buffer)
        if text.strip():
            elements.append(Paragraph(_format_text(text), self.styles["Normal"]))

    def _render_table(self, elements: list, raw_rows: list[str]) -> None:
        """Render a pipe-delimited Markdown table as a reportlab Table."""
        parsed: list[list[str]] = []
        for row in raw_rows:
            if RE_TABLE_SEPARATOR.match(row):
                continue
            cells = [c.strip() for c in row.strip("|").split("|")]
            parsed.append(cells)

        if not parsed:
            return

        num_cols = max(len(row) for row in parsed)

        # Build table data as Paragraphs
        table_data = []
        for r_idx, row_data in enumerate(parsed):
            style = self.styles["TableHeader"] if r_idx == 0 else self.styles["TableCell"]
            row_cells = []
            for c_idx in range(num_cols):
                cell_text = row_data[c_idx] if c_idx < len(row_data) else ""
                row_cells.append(Paragraph(_format_text(cell_text), style))
            table_data.append(row_cells)

        # Calculate column widths
        available = 165 * mm  # A4 width minus margins
        col_width = available / num_cols

        table = Table(table_data, colWidths=[col_width] * num_cols)
        table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.93, 0.93, 0.93)),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))

        elements.append(Spacer(1, 6))
        elements.append(table)
        elements.append(Spacer(1, 6))


# ── Merged PDF helper ────────────────────────────────────────────


def create_merged_pdf(documents: list[dict], organization_name: str = "") -> bytes:
    """Create a single PDF containing all documents, separated by page breaks.

    Each dict in ``documents`` must have keys: doc_type, title, content_md.
    Returns PDF file bytes.
    """
    buffer = io.BytesIO()
    font = _font_name()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        leftMargin=30 * mm,
        rightMargin=15 * mm,
        title="Пакет документов по 152-ФЗ",
        author=organization_name,
    )

    all_elements: list = []
    styles = _build_styles()

    for idx, doc_item in enumerate(documents):
        if idx > 0:
            # Page break between documents
            from reportlab.platypus import PageBreak
            all_elements.append(PageBreak())

        try:
            converter = MarkdownToPdfConverter(
                title=doc_item.get("title", ""),
                organization_name=organization_name,
            )
            elements = converter._parse_markdown(doc_item.get("content_md", ""))
            all_elements.extend(elements)
        except Exception as e:
            logger.error("Failed to convert %s to PDF: %s", doc_item.get("doc_type"), e)
            error_text = f"Ошибка конвертации документа {doc_item.get('doc_type', '?')}: {e}"
            all_elements.append(Paragraph(_escape_xml(error_text), styles["Normal"]))

    def header_footer(canvas, doc_template):
        canvas.saveState()
        if organization_name:
            canvas.setFont(font, 9)
            canvas.drawRightString(A4[0] - 15 * mm, A4[1] - 12 * mm, organization_name)
        canvas.setFont(font, 9)
        canvas.drawCentredString(A4[0] / 2, 12 * mm, str(canvas.getPageNumber()))
        canvas.restoreState()

    doc.build(all_elements, onFirstPage=header_footer, onLaterPages=header_footer)
    buffer.seek(0)
    return buffer.getvalue()
